AWSTemplateFormatVersion: '2010-09-09'
Description: Code pipeline for the AVSB site

Parameters:
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pCloudFormationServiceRole:
    Type: String
    Description: Common service role used by Cloudformation
  pCodeBuildServiceRole:
    Type: String
    Description: Common service role used by CodeBuild
  pAppStackName:
    Type: String
    Description: The name of the application stack
  pCodePipelineServiceRole:
    Type: String
    Description: Common service role used by CodePipeline
  pArtifactsBucket:
    Type: String
    Description: Common artifacts bucket used by CodePipeline and CodeBuild
  pGitHubRepositoryName:
    Type: String
    Description: GitHub repository name.
  pGitHubOwner:
    Type: String
    Description: GitHub owner
  pGitHubBranch:
    Type: String
    Description: GitHub branch we're deploying from
  pCodestarConnection:
    Type: String
    Description: Codestar connection ARN

Resources:
  ExportConfig:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub avsb-export-config-${pEnvironment}
      Description: Load the environment and build the CloudFormation template config file
      ServiceRole: !Ref pCodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: 'AWS_ARTIFACTS_BUCKET'
            Value: !Ref pArtifactsBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/export_config_buildspec.yaml
      TimeoutInMinutes: 5

  BuildAvsb:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub avsb-build-site-${pEnvironment}
      Description: Build the AVSB site
      ServiceRole: !Ref pCodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: 'AWS_ARTIFACTS_BUCKET'
            Value: !Ref pArtifactsBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/npm_build_buildspec.yaml
      TimeoutInMinutes: 10

  EmptyBucket:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub avsb-empty-bucket-${pEnvironment}
      Description: Empty the source s3 bucket so it can be deleted
      ServiceRole: !Ref pCodeBuildServiceRole
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        EnvironmentVariables:
          - Name: 'AWS_ARTIFACTS_BUCKET'
            Value: !Ref pArtifactsBucket
      Source:
        Type: CODEPIPELINE
        BuildSpec: cicd/empty_bucket_buildspec.yaml
      TimeoutInMinutes: 5

  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub avsb-site-${pEnvironment}
      RoleArn: !Ref pCodePipelineServiceRole
      ArtifactStore:
        Type: S3
        Location: !Ref pArtifactsBucket
      Stages:
        - Name: Checkout_Source
          Actions:
            - Name: CheckoutSrc
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref pCodestarConnection
                FullRepositoryId: !Sub ${pGitHubOwner}/${pGitHubRepositoryName}
                BranchName: !Ref pGitHubBranch
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: false
              Namespace: CheckoutSrcNS
              OutputArtifacts:
                - Name: 'AvsbSourceArtifact'
        - Name: Deploy_Infrastructure
          Actions:
            - Name: ExportConfig
              ActionTypeId:
                Owner: AWS
                Category: Build
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref ExportConfig
                EnvironmentVariables: '[
                  { "name":"SRC_BRANCH", "value":"#{CheckoutSrcNS.BranchName}" },
                  { "name":"COMMIT_ID", "value":"#{CheckoutSrcNS.CommitId}" }
                  ]'
              Namespace: ExportConfigNS
              InputArtifacts:
                - Name: 'AvsbSourceArtifact'
              OutputArtifacts:
                - Name: ExportConfigArtifact
              RunOrder: 1
            - Name: DeployCFStack
              ActionTypeId:
                Owner: AWS
                Category: Deploy
                Version: 1
                Provider: CloudFormation
              Configuration:
                TemplatePath: 'ExportConfigArtifact::cicd/avsb.yaml'
                TemplateConfiguration: 'ExportConfigArtifact::cicd/template_config.json'
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !Ref pCloudFormationServiceRole
                StackName: !Ref pAppStackName
              InputArtifacts:
                - Name: 'ExportConfigArtifact'
              Namespace: CloudFormationOutNS
              OutputArtifacts: []
              RunOrder: 2
        - Name: Publish_Website
          Actions:
            - Name: BuildAvsb
              ActionTypeId:
                Owner: AWS
                Category: Build
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref BuildAvsb
                EnvironmentVariables: '[
                  { "name":"SRC_BRANCH", "value":"#{CheckoutSrcNS.BranchName}" },
                  { "name":"COMMIT_ID", "value":"#{CheckoutSrcNS.CommitId}" }
                  ]'
              Namespace: BuildAvsbNS
              InputArtifacts:
                - Name: 'AvsbSourceArtifact'
              OutputArtifacts:
                - Name: BuildAvsbArtifact
              RunOrder: 1
            - Name: EmptyBucket
              ActionTypeId:
                Owner: AWS
                Category: Build
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref EmptyBucket
                EnvironmentVariables: '[
                  { "name":"SOURCE_BUCKET", "value":"#{ExportConfigNS.SOURCE_BUCKET}" },
                  { "name":"BUCKET_PATH", "value":"#{ExportConfigNS.BUCKET_PATH}" }
                  ]'
              Namespace: EmptyBucketPreDeployNS
              InputArtifacts:
                - Name: 'AvsbSourceArtifact'
              RunOrder: 2
            - Name: UploadFilesToS3
              ActionTypeId:
                Owner: AWS
                Category: Deploy
                Version: 1
                Provider: S3
              Configuration:
                BucketName: '#{ExportConfigNS.SOURCE_BUCKET}'
                ObjectKey: '#{ExportConfigNS.BUCKET_PATH}'
                Extract: 'true'
                CacheControl: 'public, max-age=#{ExportConfigNS.MAX_AGE}'
              OutputArtifacts: []
              InputArtifacts:
                - Name: BuildAvsbArtifact
              RunOrder: 3
        - Name: Teardown
          Actions:
            - Name: Approval
              ActionTypeId:
                Owner: AWS
                Category: Approval
                Version: 1
                Provider: Manual
              Configuration:
                CustomData: Approval required to tear down this stack
              RunOrder: 1
            - Name: EmptyBucket
              ActionTypeId:
                Owner: AWS
                Category: Build
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref EmptyBucket
                EnvironmentVariables: '[
                  { "name":"SOURCE_BUCKET", "value":"#{ExportConfigNS.SOURCE_BUCKET}" },
                  { "name":"BUCKET_PATH", "value":"#{ExportConfigNS.BUCKET_PATH}" }
                  ]'
              Namespace: EmptyBucketPreDeleteNS
              InputArtifacts:
                - Name: 'AvsbSourceArtifact'
              RunOrder: 2
            - Name: TeardownAvsb
              ActionTypeId:
                Owner: AWS
                Category: Deploy
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: DELETE_ONLY
                StackName: !Ref pAppStackName
                RoleArn: !Ref pCloudFormationServiceRole
              RunOrder: 3

Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
