version: 0.2
###
# This build project builds the AVSB site files ready for upload to s3

env:
  shell: bash

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: $NODE_VERSION
    commands:
      - echo installing pnpm...
      - curl -fsSL https://get.pnpm.io/install.sh | sh -
      - pnpm --version
      - echo installing dependencies with pnpm...
      - pnpm install
  pre_build:
    commands:
      - echo running tests...
      - pnpm test
  build:
    commands:
      - echo building...
      - pnpm build:$ENVIRONMENT

artifacts:
  base-directory: ./dist
  files:
    - "**/*"
