AWSTemplateFormatVersion: "2010-09-09"

Description: AVSB Infrastructure

Parameters:
  pAvsbWafWebAclArn:
    Description: The WAF Web ACL to attach the CloudFront distribution to
    Type: String

  pSourceBucket:
    Description: The bucket name for the site
    Type: String

  pBucketPath:
    Description: Optional path that the files are stored under
    Type: String

  pCleanBranch:
    Description: A cleaned version of the code branch name
    Type: String
    Default: development

  pEnvironment:
    Description: The AWS environment this belongs to
    Type: String

  pHostedZone:
    Description: The hosted zone the site are accessed under
    Type: String

  pSubDomain:
    Description: The subdomain the site are accessed on
    Type: String

  pSslCertificate:
    Description: The arn of the SSL certificate to be used
    Type: String

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development

  NotDev: !Not
    - !Condition IsDev

Resources:
  AvsbBucket:
    DeletionPolicy: Delete
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${pSourceBucket}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        IgnorePublicAcls: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: component
          Value: website
        - Key: Name
          Value: !Sub ${pSourceBucket}

  AvsbBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AvsbBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontService
            Action:
              - s3:GetObject
            Effect: Allow
            Resource: !Sub arn:aws:s3:::${AvsbBucket}/*
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${AvsbCloudFrontOai}
          - Sid: TLSAccessOnly
            Action:
              - s3:*
            Effect: Deny
            Resource:
              - !Sub arn:aws:s3:::${AvsbBucket}
              - !Sub arn:aws:s3:::${AvsbBucket}/*
            Principal: '*'
            Condition:
              Bool:
                aws:SecureTransport: "false"

  AvsbDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub ${pSubDomain}.${pHostedZone}
      Comment: !Sub AVSB domain for the ${pEnvironment} environment
      Type: A
      AliasTarget:
        DNSName: !GetAtt AvsbCloudFrontDistro.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub ${pHostedZone}.

  AvsbCloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    DependsOn: AvsbBucket
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub ${pSubDomain}.${pHostedZone}
        Comment: !Sub CF Distribution for the AVSB site ${pEnvironment}
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: !Ref AvsbCachePolicy
          Compress: true
          TargetOriginId: avsb-s3
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub ${pSourceBucket}.s3.${AWS::Region}.amazonaws.com
            Id: avsb-s3
            S3OriginConfig:
              OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${AvsbCloudFrontOai}
            OriginPath: !Sub /${pBucketPath}
        ViewerCertificate:
          AcmCertificateArn: !Ref pSslCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        WebACLId: !Ref pAvsbWafWebAclArn
      Tags:
        - Key: component
          Value: cdn

  AvsbCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: !Sub CF Cache Policy for the AVSB site ${pEnvironment}
        DefaultTTL: 300
        MaxTTL: 86400
        MinTTL: 1
        Name: !Sub
          - Avsb-cache-Policy-${ResourceName}
          - ResourceName: !If
              - IsDev
              - !Ref pCleanBranch
              - !Ref pEnvironment
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: whitelist
            QueryStrings:
              - cb

  AvsbCloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CF Origin Access Identity for the AVSB ${pEnvironment}

Outputs:
  AvsbBucketName:
    Value: !Ref AvsbBucket

  AvsbBucketArn:
    Value: !GetAtt AvsbBucket.Arn

  AvsbCloudFrontDistributionArn:
    Value: !Sub
      - arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}
      - DistributionId: !GetAtt AvsbCloudFrontDistro.Id
