AWSTemplateFormatVersion: '2010-09-09'
Description: AVSB Infrastructure

Parameters:
  pAvsbWafWebAclArn:
    Type: String
    Description: The WAF Web ACL to attach the CloudFront distribution to
  pSourceBucket:
    Type: String
    Description: The bucket name for the site
  pBucketPath:
    Type: String
    Description: Optional path that the files are stored under
  pCleanBranch:
    Type: String
    Description: A cleaned version of the code branch name
    Default: development
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pHostedZone:
    Type: String
    Description: The hosted zone the site are accessed under
  pSubDomain:
    Type: String
    Description: The subdomain the site are accessed on
  pSslCertificate:
    Type: String
    Description: The arn of the SSL certificate to be used

Conditions:
  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotDev: !Not [ Condition: IsDev ]

Resources:
  AvsbBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub ${pSourceBucket}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: TRUE
        BlockPublicPolicy: TRUE
        RestrictPublicBuckets: TRUE
      Tags:
        - Key: component
          Value: website
        - Key: Name
          Value: !Sub ${pSourceBucket}

  AvsbBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AvsbBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${AvsbBucket}/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${AvsbCloudFrontOai}'

  AvsbDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Sub '${pSubDomain}.${pHostedZone}'
      Comment: !Sub AVSB domain for the ${pEnvironment} environment
      Type: A
      AliasTarget:
        DNSName: !GetAtt AvsbCloudFrontDistro.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneName: !Sub '${pHostedZone}.'

  AvsbCloudFrontDistro:
    Type: AWS::CloudFront::Distribution
    DependsOn: AvsbBucket
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${pSubDomain}.${pHostedZone}'
        Comment: !Sub CF Distribution for the AVSB site ${pEnvironment}
        CustomErrorResponses:
          - ErrorCode: 403
            ErrorCachingMinTTL: 300
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: !Ref AvsbCachePolicy
          Compress: true
          TargetOriginId: avsb-s3
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub '${pSourceBucket}.s3.${AWS::Region}.amazonaws.com'
            Id: avsb-s3
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${AvsbCloudFrontOai}'
            OriginPath: !Sub '/${pBucketPath}'
        ViewerCertificate:
          AcmCertificateArn: !Ref pSslCertificate
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        WebACLId: !Ref pAvsbWafWebAclArn
      Tags:
        - Key: component
          Value: cdn

  AvsbCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Comment: !Sub CF Cache Policy for the AVSB site ${pEnvironment}
        DefaultTTL: 300
        MaxTTL: 86400
        MinTTL: 1
        Name: !Sub
          - "Avsb-cache-Policy-${ResourceName}"
          - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          EnableAcceptEncodingBrotli: true
          EnableAcceptEncodingGzip: true
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: whitelist
            QueryStrings:
              - cb

  AvsbCloudFrontOai:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub CF Origin Access Identity for the AVSB ${pEnvironment}

Outputs:
  AvsbBucketName:
    Value: !Ref AvsbBucket
  AvsbBucketArn:
    Value: !GetAtt AvsbBucket.Arn
  AvsbCloudFrontDistributionArn:
    Value: !Sub
      - "arn:aws:cloudfront::${AWS::AccountId}:distribution/${DistributionId}"
      - DistributionId: !GetAtt AvsbCloudFrontDistro.Id
